### ISSUE TITLE
Feedback for “Deployment”

### ISSUE THREAD

**Issue by isaccavalcante** [horizon-ui/boilerplate-issues#1]
I'd recommend adding more detailed instructions/commands on how to run locally, how to run with Docker and how to host with Vercel, as easy as it might be for advanced users. It would improve the dev experience for newcomers.

**Comment by simmmpleweb** [comment]
Hello, @isaccavalcante ! We made an update to the product where you can use the Supabase CLI do start and link docker to your Supabase database. We will soon add a page for the docs as well, but for the moment, you maybe [this](https://supabase.com/docs/guides/cli/getting-started) can help!
Regards, Vlad.
